### ISSUE TITLE
allow `meta git clone --single-branch --branch <branch name>`

### ISSUE THREAD

**Issue by mateodelnorte** [mateodelnorte/meta-git#10]
https://stackoverflow.com/questions/1778088/how-to-clone-a-single-branch-in-git
https://stackoverflow.com/questions/4811434/clone-only-one-branch

**Comment by RustyChain** [comment]
Hello Matt, please review my PR, it's for adding 2 optional params, one of them is specifically this.
https://github.com/mateodelnorte/meta-git/pull/17
