### ISSUE TITLE
meta fails to create annotated tag with -m option using double quotes

### ISSUE THREAD

**Issue by kevbroch** [mateodelnorte/meta-git#12]
on Unbuntu 17.10.  Doesn't seem to like the double quotes (but this works fine for `meta git commit -m "commit msg"`

Failing:
```bash
kbroch@barolo:/home/kbroch/metatest  git:(master) $ node --version
v8.9.4
kbroch@barolo:/home/kbroch/metatest  git:(master) $ meta --version
1.0.48
kbroch@barolo:/home/kbroch/metatest  git:(master) $ meta git tag -a RC -m "release candidate"

metatest:
fatal: Failed to resolve 'candidate' as a valid ref.
metatest exited with error: Error: Command failed: git tag -a RC -m release candidate

test:
fatal: Failed to resolve 'candidate' as a valid ref.
test exited with error: Error: Command failed: git tag -a RC -m release candidate

testlabelcopy:
fatal: Failed to resolve 'candidate' as a valid ref.
testlabelcopy exited with error: Error: Command failed: git tag -a RC -m release candidate
```

Passing:
```bash
kbroch@barolo:/home/kbroch/metatest  git:(master) $ meta git tag -a RC -m release-candidate  

metatest:
metatest ✓

test:
test ✓

testlabelcopy:
testlabelcopy ✓
```

**Comment by mateodelnorte** [comment]
I won't be able to take a look at this for at least a week. Mind taking a
swack at a pull request?

Cheers.

**Comment by patrickleet** [comment]
this doesn't solve your issue, @kevbroch but FYI, you should also be able to use `loop-things` for the time being, which is what meta is using under the hood.

```
npm i -g loop-things

# cd to your meta repo
# symlink .meta to .looprc
ln -s .meta .looprc

loop 'git tag -a RC -m "release candidate"'
```

**Comment by patrickleet** [comment]
my bad, looks like matt updated the name on npm.. it's just `loop` now

https://www.npmjs.com/package/loop

**Comment by kevbroch** [comment]
@patrickleet : Thanks for workaround.  
@mateodelnorte : I'm not sure I'll get time for PR either in next week but will try.

**Comment by pmanno** [comment]
Hello!

First off, thanks for the great too!  I just tried to do this same thing (using meta git tag -a v2.0 -m"some comment") and meta is decidedly unhappy with that and thinks that every character of the message is a parameter.  Any plans to get that fixed or are we just going with the workaround?

Thanks!
Paul

**Comment by patrickleet** [comment]
just use `meta exec`

`meta exec 'git tag -a v2.0 -m"some comment"'`
