### ISSUE TITLE
feat req - add path to meta git status

### ISSUE THREAD

**Issue by marct83** [mateodelnorte/meta-git#20]
Would it be possible to add the corresponding path to the output of meta git status for each of the projects in meta. It would make navigating to them much easier to do commits etc.

**Current output:**

meta-test:
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working tree clean
meta-test ✓

project-test:
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
	modified:   go.mod
	modified:   go.sum
	modified:   main.go

no changes added to commit (use "git add" and/or "git commit -a")
project-test ✓

**New Output:**

meta-test:
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working tree clean
meta-test ✓

project-test (**projects/project-test**):
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
	modified:   go.mod
	modified:   go.sum
	modified:   main.go

no changes added to commit (use "git add" and/or "git commit -a")
project-test ✓

**Comment by mateodelnorte** [comment]
I'll look into it. IIRC, it was kind of a PITA. If it's an easy fix, I'll throw it in there. Otherwise, we can potentially throw it in as a part of a larger refactor coming up.

**Comment by mateodelnorte** [comment]
There's also the tradeoff between having a nice, succinct looking command line – versus having a /big/long/file/path/taking/up/screen/space/everywhere.

**Comment by marct83** [comment]
I see what you mean. Is there a way to do a commit/add  from the root of the meta project?

meta git commit -a -m doesnt seem to work

**Comment by mateodelnorte** [comment]
should work fine. be sure you put quotes around your commit message, and make sure you're in the root where the .meta file is.

**Comment by marct83** [comment]
That works. Can I specify which project I want to run the commit against?

**Comment by mateodelnorte** [comment]
If you just have a single project to run a commit against, just cd into that directory and use a normal git command. If you have a commit to make on a number of repos, use `meta git commit -am "bla bla"`. You can constrain this to specific repos by using loop options shown [here](https://github.com/mateodelnorte/loop). (see --include-only and --exclude)
