### ISSUE TITLE
Problem running `pull --rebase origin master`

### ISSUE THREAD

**Issue by meredian** [mateodelnorte/meta-git#21]
Hello!

I've encountered consistent problem, while trying to run typical git pattern. When running `meta git pull --rebase {remote} {branch}`, `git-meta` instead runs `git pull {branch} --rebase {remote}`, which is not a working thing.

Git version 2.17.0
Os: MacOS 10.13 (`Darwin 17.7.0 Darwin Kernel Version 17.7.0`)

Here's specific example output:
```
➜  meta git:(feature/xxxx) ✗ meta git pull --rebase origin master

meta:
fatal: 'master' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
meta: command 'git pull master --rebase origin' exited with error: Error: Command failed: git pull master --rebase origin
```

I would like to deal with issue on my own, since it will make my life much easier :)
1) Please confirm it's a bug, or it should be done in some other way.
2) Maybe there are any use cases, when this behaviour is correct, so I do not miss them?
3) Any recommendations on contributing to the code are welcome, but not mandatory :)

**Comment by mateodelnorte** [comment]
Hi @meredian. Happy to field a pull request. Thanks!
