### ISSUE TITLE
meta git remote

### ISSUE THREAD

**Issue by mikelax** [mateodelnorte/meta-git#3]
Implement git [remote sub-command](https://git-scm.com/book/be/v2/Git-Basics-Working-with-Remotes). I would think at the minimum the following sub-commands would be useful.

* git remote -v
* git remote show origin
* git remote rename oldname newname
* git remote rm name

**Comment by mateodelnorte** [comment]
Happy to add this! I've created https://github.com/mateodelnorte/meta-git/pull/4 to house the work, and got started with `-v` and `show origin`. 

Interested in contributing? Would love to have a second pair of eyes on the patterns I'm using as well. 

**Note I plan to refactor everything from line 47 to eof to a module, so you can just say something like `metaLoop(command);`, which will make all the plugin commands much more terse.

**Comment by mikelax** [comment]
cool, I just started to look things over. I'll spend a bit more time with this and then the main meta project to see if I can help at all with the node-gh integration.

**Comment by mateodelnorte** [comment]
fixed by PR #4
