### ISSUE TITLE
Run git commands on all branches

### ISSUE THREAD

**Issue by eddex** [mateodelnorte/meta-git#55]
## 🚀 Feature Proposal

Run git commands on all available branches using something like `--all-branches`.

## Motivation

Working on a project with many repos, I often find myself working on multiple branches of the same repo when I collaborate with multiple members of my team. It would be nice to have a simple way to see all the local changes I currently have on all those branches in a simple way.

## Example

```bash
➜  meta-repo git:(master) meta git status --all-branches

/path/to/my/repos/repo1: 
On branch master 
nothing to commit, working tree clean
/path/to/my/repos/repo1: ✓

/path/to/my/repos/repo1: 
On branch feat-1
nothing to commit, working tree clean
/path/to/my/repos/repo1: ✓

...
```

**Comment by mateodelnorte** [comment]
This would be fairly complex, as you'd have to query the set of branches on every repo. That set of branches would likely be long and not curated, for most people. It's also not a standard git command, so my inclination is to not support.
